-- Kladen metadata schema for Oracle Autonomous DB (run as ADMIN, or as a
-- dedicated KLADEN schema user). Mirrors backend/api.py's SQLite model plus
-- dual-mode profiles (manual vs vault) and object-storage artifact pointers.
--
-- Timestamps and summary_json are VARCHAR2, not TIMESTAMP/CLOB, on purpose:
-- the app stores ISO-8601 UTC strings and small JSON text, so keeping these as
-- VARCHAR2 lets one set of SQL run unchanged on both SQLite and Oracle (no
-- datetime binding or LOB handling). created_at defaults to an ISO UTC string.
--
-- What lives here (metadata only): orgs, clients, stacks, runs, profiles as
-- POINTERS, users, approvals. Blobs (logs, plan.json, reports, state, keys)
-- live in Object Storage / Vault; this DB stores only their locations.
--
-- Idempotent-ish: drops are commented so a re-run doesn't wipe data. Uncomment
-- the DROP block for a clean rebuild.

-- ---- clean rebuild (uncomment to wipe) -----------------------------------
-- BEGIN
--   FOR t IN (SELECT table_name FROM user_tables
--             WHERE table_name IN ('RUNS','STACKS','PROFILES','CLIENTS','USERS','ORGS')) LOOP
--     EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS';
--   END LOOP;
-- END;
-- /

-- ---- orgs (the Kladen customer / MSP workspace) --------------------------
CREATE TABLE orgs (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(200) NOT NULL,
  created_at  VARCHAR2(40) DEFAULT TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS"+00:00"') NOT NULL
);

-- ---- users (login identities; role gates access) -------------------------
CREATE TABLE users (
  id            VARCHAR2(64) PRIMARY KEY,          -- app-generated id
  org_id        NUMBER NOT NULL REFERENCES orgs(id),
  client_id     NUMBER,                            -- tenant scope: NULL = workspace-wide (super-admin/staff), else one customer. No inline FK: clients is defined below (Oracle forbids forward refs); app enforces scope.
  name          VARCHAR2(200) NOT NULL,
  email         VARCHAR2(320) UNIQUE,
  role          VARCHAR2(20)  NOT NULL,            -- junior | senior | management | admin
  password_hash VARCHAR2(200),                     -- pbkdf2$iters$salt$hash
  created_at    VARCHAR2(40) DEFAULT TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS"+00:00"') NOT NULL
);
-- Existing ATP created before per-customer isolation: ALTER TABLE users ADD (client_id NUMBER);

-- ---- clients (each has its own OCI tenancy/credentials) ------------------
CREATE TABLE clients (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id      NUMBER NOT NULL REFERENCES orgs(id),
  name        VARCHAR2(200) NOT NULL,
  created_at  VARCHAR2(40) DEFAULT TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS"+00:00"') NOT NULL
);

-- ---- profiles (OCI credentials, dual-mode) -------------------------------
-- source = 'manual'    : creds stored in the columns below; key on disk at key_path
--          'oci-config': imported from ~/.oci/config
--          'vault'      : creds live in OCI Vault; secret_ocid points to them,
--                         and the credential columns stay NULL (fetched at run time)
CREATE TABLE profiles (
  id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id            NUMBER NOT NULL REFERENCES orgs(id),
  client_id         NUMBER REFERENCES clients(id),   -- NULL = org/workspace default
  name              VARCHAR2(200) NOT NULL,
  -- Oracle treats '' as NULL, so DEFAULT '' NOT NULL is self-contradictory and
  -- breaks inserts; these optional text columns are simply nullable instead.
  env               VARCHAR2(40),
  source            VARCHAR2(20)  DEFAULT 'manual' NOT NULL,
  region            VARCHAR2(60),
  -- manual-mode credential fields (NULL when source='vault')
  tenancy_ocid      VARCHAR2(255),
  user_ocid         VARCHAR2(255),
  fingerprint       VARCHAR2(120),
  key_path          VARCHAR2(1000),
  compartment_ocid  VARCHAR2(255),
  -- vault-mode pointers (NULL when source!='vault')
  vault_id          VARCHAR2(255),
  secret_ocid       VARCHAR2(255),
  created_at        VARCHAR2(40) DEFAULT TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS"+00:00"') NOT NULL,
  CONSTRAINT profiles_source_ck CHECK (source IN ('manual','oci-config','vault')),
  CONSTRAINT profiles_mode_ck CHECK (
    (source = 'vault'  AND secret_ocid IS NOT NULL) OR
    (source <> 'vault' AND tenancy_ocid IS NOT NULL AND user_ocid IS NOT NULL
                       AND fingerprint IS NOT NULL AND key_path IS NOT NULL)
  )
);

-- ---- stacks --------------------------------------------------------------
CREATE TABLE stacks (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id   NUMBER NOT NULL REFERENCES clients(id),
  name        VARCHAR2(200) NOT NULL,
  env         VARCHAR2(40)  NOT NULL,
  profile_id  NUMBER REFERENCES profiles(id),  -- pin; NULL = resolve by scope
  workspace   VARCHAR2(1000),                  -- object-storage prefix or local path
  created_at  VARCHAR2(40) DEFAULT TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS"+00:00"') NOT NULL
);

-- ---- runs ----------------------------------------------------------------
-- Small columns here; big outputs go to Object Storage under artifacts_prefix.
-- NB: `mode` is a reserved word in Oracle, so the column is `run_mode`; the
-- backend maps it to the API/JSON field "mode" (SELECT run_mode AS mode).
CREATE TABLE runs (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stack_id         NUMBER NOT NULL REFERENCES stacks(id),
  run_mode         VARCHAR2(20)  NOT NULL,      -- validate | plan | apply | destroy
  status           VARCHAR2(30)  NOT NULL,      -- queued|running|awaiting_approval|succeeded|failed|rejected
  created_at       VARCHAR2(40) DEFAULT TO_CHAR(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS"+00:00"') NOT NULL,
  started_at       VARCHAR2(40),
  finished_at      VARCHAR2(40),
  requested_by     VARCHAR2(200) DEFAULT 'system' NOT NULL,
  approved_by      VARCHAR2(200),
  detail           VARCHAR2(2000),
  summary_json     VARCHAR2(4000) DEFAULT '{}' NOT NULL,  -- {create,update,delete} counts
  artifacts_prefix VARCHAR2(1000),              -- os://<bucket>/runs/<id>/ ; logs live there
  CONSTRAINT runs_run_mode_ck CHECK (run_mode IN ('validate','plan','apply','destroy'))
);

-- ---- indexes -------------------------------------------------------------
CREATE INDEX ix_clients_org      ON clients(org_id);
CREATE INDEX ix_profiles_client  ON profiles(client_id);
CREATE INDEX ix_stacks_client    ON stacks(client_id);
CREATE INDEX ix_runs_stack       ON runs(stack_id);
CREATE INDEX ix_runs_created     ON runs(created_at DESC);

COMMIT;
